version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.13.1
    branches:
      only:
        - appSetup
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }
            - v1-dependencies-
      - checkout
      - run: npm install
      - run: npm test
      - save_cache:
          keys:
            - v1-dependencies-{{ checksum package.json }}
            - v1-dependencies-
