version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.13.1
    branches:
      only:
        - appSetup
    steps:
      - checkout
      - run: npm install
      - run: node ./test/index.test.js