version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6.13.1
    branches:
      only:
        - appSetup
    steps:
      - checkout
      - restore_cache:
          keys: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - run: npm test
      - save_cache:
          key: v1-dependencies-{{ checksum package.json }}
            paths:
              - node_modules